images:
  vsphereCloudControllerManager: "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.1.0"
  csiAttacher: "quay.io/k8scsi/csi-attacher:v1.1.1"
  csiDriver: "gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.2"
  livenessProbe: "quay.io/k8scsi/livenessprobe:v1.1.0"
  vsphereSyncer: "gcr.io/cloud-provider-vsphere/csi/release/syncer:v1.0.2"
  csiProvisioner: "quay.io/k8scsi/csi-provisioner:v1.2.2"
  nodeDriverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v1.1.0"

vcenter:
  # host: vcenter.example.com
  insecurehost: true
  # username: admin 
  # password: root
  # datacenter: DC1

storageclass:
  name: vsphere-csi
  default: true
  fstype: ext4
  # storagepolicyname: my-storage-policy
  # datastoreurl: ds:///vmfs/volumes/vsan:528c27f173c2088e-2126e911985dc3aa/
